spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/zenthera_db
    username: postgres
    password: CAMBIAR_EN_PRODUCCION
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: "CAMBIAR_A_UN_SECRETO_SEGURON_PRODUCCION"
  expiration-ms: 86400000

server:
  port: 8080