CREATE TABLE historia_clinica (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clinica_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historia_clinica_clinicas FOREIGN KEY (clinica_id) REFERENCES clinicas(id) ON DELETE CASCADE,
    CONSTRAINT fk_historia_clinica_pacientes FOREIGN KEY (paciente_id) REFERENCES pacientes(id) ON DELETE CASCADE,
    CONSTRAINT uq_historia_clinica_paciente_clinica UNIQUE (clinica_id, paciente_id)
);

CREATE TABLE consulta_clinica (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    historia_clinica_id BIGINT NOT NULL,
    clinica_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    motivo_consulta TEXT,
    sintomas_observaciones TEXT,
    peso NUMERIC(5,2),
    talla NUMERIC(5,2),
    presion_sistolica INTEGER,
    presion_diastolica INTEGER,
    frecuencia_cardiaca INTEGER,
    temperatura NUMERIC(4,1),
    saturacion_oxigeno INTEGER,
    diagnostico_inicial TEXT,
    tratamiento_indicaciones TEXT,
    notas TEXT,
    finalizada_at TIMESTAMP WITH TIME ZONE,
    finalizada_por BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consulta_clinica_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id) ON DELETE CASCADE,
    CONSTRAINT fk_consulta_clinica_clinicas FOREIGN KEY (clinica_id) REFERENCES clinicas(id) ON DELETE CASCADE,
    CONSTRAINT fk_consulta_clinica_medicos FOREIGN KEY (medico_id) REFERENCES medicos(id),
    CONSTRAINT fk_consulta_clinica_finalizada_por FOREIGN KEY (finalizada_por) REFERENCES usuarios(id)
);

CREATE INDEX idx_historia_clinica_paciente ON historia_clinica(paciente_id);
CREATE INDEX idx_consulta_clinica_historia ON consulta_clinica(historia_clinica_id);
CREATE INDEX idx_consulta_clinica_medico ON consulta_clinica(medico_id);
