-- V1_1__init_core_schema.sql
-- Propósito: Inicializar el esquema base (clinicas, roles, usuarios) que originalmente
-- se generaba vía Hibernate ddl-auto=create. Esta migración es necesaria para levantar
-- una base de datos en blanco (como en el perfil e2e_clean) y poder aplicar V2 a V8
-- exitosamente sin errores de dependencias faltantes.
CREATE TABLE IF NOT EXISTS clinicas (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( SEQUENCE NAME clinicas_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    activa boolean NOT NULL,
    ciudad character varying(100),
    correo character varying(120),
    direccion text,
    logo character varying(255),
    nombre character varying(150) NOT NULL,
    pais character varying(80),
    provincia character varying(100),
    ruc character varying(13),
    telefono character varying(20),
    CONSTRAINT clinicas_pkey PRIMARY KEY (id),
    CONSTRAINT uk_clinica_ruc UNIQUE (ruc)
);

CREATE TABLE IF NOT EXISTS roles (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( SEQUENCE NAME roles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    descripcion character varying(255),
    nombre character varying(50) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT uk_rol_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( SEQUENCE NAME usuarios_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    activo boolean NOT NULL,
    apellidos character varying(120) NOT NULL,
    cedula character varying(20) NOT NULL,
    correo character varying(120) NOT NULL,
    foto character varying(255),
    nombres character varying(120) NOT NULL,
    password character varying(255) NOT NULL,
    telefono character varying(20),
    ultimo_login timestamp(6) without time zone,
    clinica_id bigint NOT NULL,
    rol_id bigint NOT NULL,
    bloqueado boolean NOT NULL,
    cambiar_password boolean NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT uk_usuario_cedula UNIQUE (cedula),
    CONSTRAINT uk_usuario_correo UNIQUE (correo),
    CONSTRAINT fk_usuario_clinica FOREIGN KEY (clinica_id) REFERENCES clinicas(id),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES roles(id)
);
