-- V4: Creación de tabla para Refresh Tokens

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE, -- SHA-256 (64 hex chars)
    familia_id VARCHAR(36) NOT NULL, -- UUID de la familia de sesión
    usuario_id BIGINT NOT NULL,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    revocado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_refresh_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Indice para búsquedas rápidas por usuario
CREATE INDEX idx_refresh_token_usuario ON refresh_tokens(usuario_id);
-- Indice para buscar la familia entera y revocarla rápidamente
CREATE INDEX idx_refresh_token_familia ON refresh_tokens(familia_id);
